language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-angular-halffull' ]; then cd .. && eval "mv $currentfolder generator-angular-halffull" && cd generator-angular-halffull; fi

